package com.carrental.backend.model;

public enum UserPermission {
    VIEW_HOME_DASHBOARD,
    VIEW_RESERVATIONS,
    VIEW_TODAYS_RESERVATIONS,
    VIEW_INTERNAL_MESSAGES,
    VIEW_FLEET_AVAILABILITY,
    VIEW_MY_PROFILE,
    ACTION_RESERVATIONS_ADD,
    ACTION_RESERVATIONS_EDIT,
    ACTION_RESERVATIONS_DELETE,
    ACTION_RESERVATIONS_EXTEND,          // new
    ACTION_RESERVATIONS_UPGRADE,          // new
    ACTION_RESERVATIONS_VIEW_VOUCHER,     // new
    VIEW_REPORTS_YEARLY_SUMMARY,
    VIEW_REPORTS_SOURCE_PERFORMANCE,
    VIEW_REPORTS_INVOICE_GENERATION,
    VIEW_FINANCIALS_ACCOUNTING,
    VIEW_FINANCIALS_PAYMENT_APPROVALS,
    VIEW_FINANCIALS_DEFERRED_PAYMENTS,
    VIEW_FINANCIALS_LATE_RETURNS,
    VIEW_TRAFFIC_TICKETS,
    VIEW_VEHICLE_DAMAGES,
    VIEW_ADMIN_PANEL,
    ACTION_ADMIN_MANAGE_USERS,
    ACTION_ADMIN_MANAGE_FLEET,
    ACTION_ADMIN_MANAGE_SOURCES,
    ACTION_ADMIN_MANAGE_EXTRAS,
    ACTION_ADMIN_MANAGE_LOCATIONS,
    ACTION_ADMIN_MANAGE_COMPANY_DETAILS,
    ACTION_ADMIN_MANAGE_YEARS,
    VIEW_SYSTEM_ACTIVITY_LOG,
    VIEW_AGGREGATOR_SETUP
}
